apiVersion: v1
kind: Service
metadata:  
  name: tcp
  labels:
    app: tcp
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: tcp
spec:
  type: ClusterIP
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "8883"
    port: 8883
    targetPort: 8883
  - name: "5684"
    port: 5684
    targetPort: 5684
  
  selector:
    app: tcp
    release: {{ .Release.Name }}
    component: tcp
status:
  loadBalancer: {}

