apiVersion: v2
description: A Helm chart for Piraeus Monitoring
name: piraeus-monitor
version: 0.0.3
icon: https://avatars2.githubusercontent.com/u/25301165?s=400&v=4
appVersion: 0.0.3
keywords:
  - piraeus 
  - monitor
home: https://github.com/skunklab/piraeus
sources:
  - https://github.com/skunklab/piraeus
maintainers:
  - name: Matt Long
    email: malong@microsoft.com
tillerVersion: ">=2.7.0-rc1"